### ISSUE TITLE
com.vaguehope.cdsc.CDSCBaseListener doesn't exist

### ISSUE THREAD

**Issue by nospam2k** [haku/dlnatoad#14]
Trying to run from Intellij Idea. No com.vaguehope.cdsc

**Comment by haku** [comment]
I don't know anything about how IDEA handles Maven plugins, but it sounds like its not invoking antlr4-maven-plugin (which is used to convert the search grammar file into classes).

This is an untested guess, but perhaps https://github.com/antlr/intellij-plugin-v4 might help?

**Comment by nospam2k** [comment]
My basic interest has been to try and learn how to send an image to a dlna mediarenderer so from what I've learned about DLNA over the past several hours (starting from 0), I realize this project won't help with that so if you want to close this issue or leave it open. I won't have time to work out the problem. Thanks for getting back to me.

**Comment by haku** [comment]
This project will expose static images as DLNA resources that other devices can browse.
But if you want to control a render device and tell it to do something you will also need to implement a control point.
After device discovery etc has happened its basically two RPCs:
SetAVTransportURI()
Play()

Its not a clean example, but I do have another project that does all this, although its more music focused.  As a vague starting point, this is its wrapper around the Cling calls:
https://github.com/haku/MorriganDLNA/blob/master/com.vaguehope.morrigan.dlna/src/com/vaguehope/morrigan/dlna/players/AvTransportActions.java

**Comment by nospam2k** [comment]
Haku, I REALLY appreciate this info. What I'm after is I have a DLNA mediaRenderer projector that I just want to send an image to persist on until I change it or stop it so. I've figured out the two calls using curl but it didn't show the image so I'll look at your example. For that, I'll take the time to work on making this project work with intellij so let's keep this open. I look into it next week. If there is anything special about persisting an image, I'd appreciate that info. Once we are done, I'll clean up my entries here.

**Comment by nospam2k** [comment]
Ok, I'm kinda going around in circles. What is the minimum required to send an image to a DLNA AVTransport service? Can it just be an http server uri or does it need to be a DLNA server? Also can I do without metadata? I noticed looking at the code for cling there seems to be a method without metadata, but I'm really new to DLNA.
